import { Payment } from "./types";

export const sampleData: Payment[] = [
  {
    id: "m5gr84i9",
    amount: 316,
    status: "success",
    email: "ken99@example.com",
    customer: "Kenya Nor",
    date: "25/04/09",
    pfp: "",
  },
  {
    id: "3u1reuv4",
    amount: 242,
    status: "success",
    email: "Abe45@example.com",
    customer: "abe",
    date: "25/04/09",
    pfp: "",
  },
  {
    id: "derv1ws0",
    amount: 837,
    status: "pending",
    email: "Monserrat44@example.com",
    customer: "mon",
    date: "25/04/09",
    pfp: "",
  },
  {
    id: "5kma53ae",
    amount: 874,
    status: "success",
    email: "Silas22@example.com",
    customer: "sil",
    date: "25/04/09",
    pfp: "",
  },
  {
    id: "bhqecj4p",
    amount: 721,
    status: "pending",
    email: "carmella@example.com",
    customer: "car",
    date: "25/04/09",
    pfp: "",
  },
  {
    id: "bhqecj4p",
    amount: 721,
    status: "pending",
    email: "carmella@example.com",
    customer: "car",
    date: "25/04/09",
    pfp: "",
  },
  {
    id: "bhqecj4p",
    amount: 721,
    status: "pending",
    email: "carmella@example.com",
    customer: "car",
    date: "25/04/09",
    pfp: "",
  },
  {
    id: "bhqecj4p",
    amount: 721,
    status: "pending",
    email: "carmella@example.com",
    customer: "car",
    date: "25/04/09",
    pfp: "",
  },
];
