import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AppSidebar } from "@/components/AppSidebar";
import { cookies } from "next/headers";
import { createClientServer } from "@/lib/supabase/server";

export const metadata: Metadata = {
  title: "Invoicely / dashboard",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  //using cookies so tht u persist the open/close state of the sidebar after subsequent rerenders
  const cookieStore = await cookies();
  const supabase = await createClientServer();

  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  const {
    data: { user },
  } = await supabase.auth.getUser();

  console.log(user);

  return (
    <SidebarProvider defaultOpen={defaultOpen}>
      <AppSidebar user={user} />
      <main className="w-full">
        <div className="h-12 flex items-center">
          <SidebarTrigger />
          <span>|</span>
          <span className="ml-2">Dashboard / Route</span>
        </div>
        <div className="bg-gray-50 h-dvh w-full">{children}</div>
      </main>
    </SidebarProvider>
  );
}
